remote_theme: pages-themes/hacker@v0.2.0
plugins: - jekyll-remote-theme
title: DataMan, by McCollum Joseph
description: bookmark this project to stay up to date with updates/new versions of this project
github: https://github.com/mccollum32
github_username: mccollum32
